Repository devtayade/Product-Designer-Portfolio-, pull requests merged in 2022-10, with the labels that each got.

#22 Added new Footer
  assets/css/styles.css
  index.html
Labels: hacktober-accepted

#24 Update index.html
  index.html
Labels: hacktober-accepted

#17 Added navbar in the css
  assets/css/styles.css
  index.html
Labels: hacktober-accepted

#25 Update index.html
  index.html
Labels: enhancement

#28 Added Updated Navbar
  assets/css/navbar.css
  assets/js/navbar.js
  index.html
  jquery-3.6.1.min.js
Labels: hacktober-accepted, Great PR

#29 added achievements section
  index.html
Labels: hacktober-accepted

#34 changed design of contact us section
  .vscode/settings.json
  assets/css/styles.css
  assets/img/116-1166356_customer-service-illustration-call 1.png
  assets/img/116-1166356_customer-service-illustration-call.png
  index.html
Labels: hacktober-accepted

#36 #21 Fixed the footer design
  assets/css/styles.css
  index.html
Labels: hacktober-accepted

#38 Added Cover letter
  README.md
Labels: hacktober-accepted

#39 Created License.md
  License.md
Labels: hacktober-accepted

#42 cursor updated
  asets/css/styles.css
Labels: hacktober-accepted

#43 Hackoctoberfest-2022
  web apps.json
Labels: hacktober-accepted

#45 Skills Percentage
  index.html
  skills.css
Labels: hacktober-accepted

#46 fix: changed styling and added dark mode toggle button
  .vscode/settings.json
  assets/139-removebg-preview.png
  assets/css/styles.css
  assets/icons8-behance-48.png
  assets/icons8-dribbble-48.png
  assets/icons8-github-48.png
  assets/icons8-linkedin-48.png
  index.html
Labels: hacktober-accepted

#48 Patch 1
  assets/css/myProjects.css
  index.html
Labels: hacktober-accepted

#49 Resolving issue #44.
  assets/css/styles.css
Labels: hacktober-accepted

#50 Achievement and Services Cards
  assets/css/navbar.css
  assets/css/styles.css
  cards.css
  index.html
  skills.css
Labels: hacktober-accepted

#51 Issue #26 Added testimonials section
  assets/css/styles.css
  assets/img/testImg1.jpg
  assets/img/testImg2.jpg
  assets/img/testImg3.jpg
  index.html
Labels: hacktober-accepted

#53 complete UI updated
  assets/css/myProjects.css
  assets/css/styles.css
  cards.css
  index.html
  skills.css
Labels: hacktober-accepted

#55 made responsive
  assets/css/styles.css
  cards.css
  index.html
  skills.css
Labels: hacktober-accepted
